version: '3'
services:
  frontend:
    build:
      context: ./my-frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./my-backend-app
    ports:
      - "9040:9040"

